import Mongoose = require("mongoose");
import {Types} from 'mongoose';
import {field, document} from '../../mongoose/decorators';
import {Strict} from '../../mongoose/enums/';
import {onetomany, manytoone, manytomany, onetoone} from '../../core/decorators';

// Each article will have title, description and author. 
// All the links from parent will have parent, category, complete content and title and description (if available)
@document({ name: 'article', strict: Strict.false, searchIndex: true })
export class article {

    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    content: string;

    @field()
    description: string;

    @field()
    title: string;

    @field()
    author: string;

    @field()
    category: string;
}

export default article;