/// <reference path="../../core/dynamic/crud.entity.ts" />
import {field, document} from '../../mongoose/decorators'; 
import {Types} from 'mongoose';
import {CrudEntity} from '../../core/dynamic/crud.entity';
export class baseModel extends CrudEntity {
 
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;


    
}

export default baseModel;