import {field, document} from '../../src/mongoose/decorators';
import {Types} from 'mongoose';

export class baseModel {
  constructor(object?: any) {
  }

  @field({primary: true, autogenerated: true})
  _id: Types.ObjectId;

  @field()
  name: String;
}

export default baseModel;
