import {onetomany, manytoone, manytomany, jsonignore, required} from '../../../src/core/decorators';
import {field, document} from '../../../src/mongoose/decorators';
import {IRole} from './role';
import * as UM from './usermodel';
import {Strict} from '../../../src/mongoose/enums/';
import {JsonIgnore} from '../../../src/core/enums/jsonignore-enum';

@document({name: 'roles', strict: Strict.false})
export class RoleModel {
  @field({primary: true, autogenerated: true})
  _id: any;

  @field()
  name: any;


  @field()
  @required()
  test: any;

  constructor(userDto: IRole) {
    this._id = userDto._id;
    this.name = userDto.name;
  }
}

export default RoleModel;
